var nom = "x";
var habite = "y";
var pays = "belgium";
var metier = "web developper";
var marié = "z";
var enfants ="N";
console.log("vous serez " +nom + " et habiterez " +pays + " et marié à " +marié + " avec " + enfants + " enfants");
var annéescourantes = 2018;
var annéesdenaissances = 1998;
console.log(annéescourantes-annéesdenaissances)
var myage = 20; 
var agemax =100;
var foods =1000000;
var consofoodperday = 2;
console.log( + foods-consofoodperday + " de " + foods + " avant d'atteindre l'age " + agemax + " ans");
var result = (1 + 2) * 3 + 4 / 2;
console.log(result);
var diviser = 4/2;
var add = (1+2);
var multi =3;
console.log(diviser + multi*add);
